name: chess_shared
description: a collection of classes and functions to support chess_ui and core_chess packages.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  equatable: ^2.0.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
